name: PHP Unit

on: [push, pull_request]

jobs:
    build-test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: php-actions/composer@v6
            - name: Run tests
              uses: php-actions/phpunit@v3
              with:
                  version: latest
                  php_version: "8.2"
                  test_suffix: "Test.php"
